### ISSUE TITLE
Missing test or constrains in Chapter 3 about applying Schema to propertyName

### ISSUE THREAD

**Issue by LasneF** [json-schema-org/tour#95]
there might missing either a test case either , the validation is not tuned correctly
i am refering to Chapter 3 about applying Schema to propertyName

given this 

```
{
  "type": "object",
  "minProperties": 2,
  "propertyNames": {
    "pattern": "^[A-Z]+$"
  },
  "additionalProperties": {
    "type": [
      "string",
      "integer"
    ]
  }
}

```
I got a success whereas it does not comply witht the constrains 
The property names should be written in capital letters, and should have **minimum length of 3 characters**.

**Comment by LasneF** [comment]
adding on top of it that the solution proposed is leveraging an invalid keyword minimumLength vs it should be minLength

```
{
  "type": "object",
  "minProperties": 2,
  "propertyNames": {
    "pattern": "^[A-Z]+$",
    "minimumLength": 3
  },
  "additionalProperties": {
    "type": [
      "string",
      "integer"
    ]
  }
}
```

**Comment by gregsdennis** [comment]
What is this lesson trying to highlight?

This task can be accomplished with just `pattern: ^[A-Z]{3,}$`.

If it's trying to teach `minLength`, we should drop the all caps requirement since that allows a solution that doesn't require `minLength`.

**Comment by LasneF** [comment]
the trainning is this one , introducing propertyNames 
https://tour.json-schema.org/content/03-Objects/04-Applying-Schema-to-Property-Names 

it is about having propertyNames definition that should follow a schema 

i can do a PR for switching the right vocabulary about minLength <=> minimumLength 

then i am not sure of the validator because there is a test case testing with that should fails according to the constrains 

The property names should be written in capital letters, and **should have minimum length of 3 characters.**

{
  "NAME": "JOhN DOE",
  "AGE": 16,
  "ph": "123"
}

so it s may be about the constrains that looks not set properly will have a look on spare time how all that works

**Comment by gregsdennis** [comment]
I tried my solution

```json
{
  "type": "object",
  "propertyNames": {
    "pattern": "^[A-Z]{3,}$"
  }
}
```

and I agree that something's wrong with the validation.

Cases 1 and 3 should always evaluate the same.

```jsonc
// case 1
{
  "NAME": "JOhN DOE",
  "AGE": null
}

// case 3
{
  "NAME": "John Doe",
  "AGE": 16
}
```

They have the same property names.  However for this schema, case 1 fails and case 3 passes.  I'm not sure how that works.

**Comment by JeelRajodiya** [comment]
@LasneF 
Can please you check now if the issue still persists?

**Comment by LasneF** [comment]
issue is fixed @JeelRajodiya  , closing the ticket

**Comment by gregsdennis** [comment]
@LasneF @JeelRajodiya the issue is not fixed.  My schema still doesn't pass the first two test cases.  Those cases should validate, but the lesson requires that they don't.

**Comment by gregsdennis** [comment]
Okay.  It looks like there were other requirements that I didn't see until just now.

That said, the suggested solution still doesn't pass the first test case.
